// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2FKMET9-vt4fWQ1FZleQepqaLfQE8ycE',
    appId: '1:1078125384820:web:54d0192c9c3ebd5a7e6d21',
    messagingSenderId: '1078125384820',
    projectId: 'fir-tutorial-39cf3',
    authDomain: 'fir-tutorial-39cf3.firebaseapp.com',
    storageBucket: 'fir-tutorial-39cf3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxJL2WYVIYRaUhNg0eru7bmd1wDEnLQoY',
    appId: '1:1078125384820:android:e5b539a7518526177e6d21',
    messagingSenderId: '1078125384820',
    projectId: 'fir-tutorial-39cf3',
    storageBucket: 'fir-tutorial-39cf3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjyFE6nyGosKeKc567ltMUPJ1hmCPcGWs',
    appId: '1:1078125384820:ios:b1e2a8b4b3f7dcb67e6d21',
    messagingSenderId: '1078125384820',
    projectId: 'fir-tutorial-39cf3',
    storageBucket: 'fir-tutorial-39cf3.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjyFE6nyGosKeKc567ltMUPJ1hmCPcGWs',
    appId: '1:1078125384820:ios:b1e2a8b4b3f7dcb67e6d21',
    messagingSenderId: '1078125384820',
    projectId: 'fir-tutorial-39cf3',
    storageBucket: 'fir-tutorial-39cf3.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );
}
